# Runs the bare-metal OpenResty config (config/openresty, generated by
# build-baremetal-config.sh) inside a container, purely so this harness can
# stand it in for the `openresty` systemd unit that cutover-from-baremetal.sh
# expects to find - this is a test harness, not a second deployment target.
#
# Copied from proxy/differential/baremetal.Dockerfile (sibling PR #1977,
# branch claude/proxy-differential-tests) rather than depended on - see
# proxy/deploy/e2e/README.md. Keep the two in sync; whichever of #1977 / this
# PR merges second should dedupe them.
#
# It is built FROM the already-built proxy image so both sides run the
# identical OpenResty binary and vendored Lua libs (lua-resty-auto-ssl,
# lua-resty-http, dehydrated, sockproc - see proxy/Dockerfile) and only the
# generated nginx config differs. It skips proxy/entrypoint.sh's envsubst
# rendering (config/openresty/build-config.js already bakes real values into
# the template, unlike the container's ${PROXY_*} placeholders) and the
# container-only health socket - bare metal has none either.
ARG PROXY_IMAGE=blot-proxy:e2e
FROM ${PROXY_IMAGE}

# The bare-metal generator (config/openresty/build-config.js) is run with
# OPENRESTY_LOG_DIRECTORY / OPENRESTY_CACHE_DIRECTORY / OPENRESTY_CONFIG_DIRECTORY
# pointed at these same paths (see build-baremetal-config.sh), which the base
# image already creates and chowns to ec2-user (proxy/Dockerfile).
COPY config/openresty/data/latest/openresty.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY config/openresty/data/latest/cacher.lua /etc/openresty/cacher.lua
COPY config/openresty/data/latest/html /etc/openresty/html

# No ${PROXY_*} placeholders to fill in and no health socket to create -
# start OpenResty directly instead of proxy/entrypoint.sh.
ENTRYPOINT ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
