module.exports = {
  id: "string",
  name: "string",
  slug: "string",
  owner: "string",
  cloneFrom: "string",
  shareID: "string",
  errors: "object",
  previewPath: "string",
  description: "string",
  localEditing: "boolean",
  thumb: "string",
  locals: "object",
  cdn: "object",
};
